import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  projectsOverviewSidebar: [
    "overview",
    "overview-test-alpha",
    "overview-test-alpha-child",
    "overview-test-beta",
    "overview-test-beta-child",
  ],
  sampleProjectSidebar: [{ type: "autogenerated", dirName: "sample-project" }],
};

export default sidebars;
