import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  notesOverviewSidebar: ["overview", "status-system"],
  machineLearningSidebar: [{ type: "autogenerated", dirName: "machine-learning" }],
  computerScienceSidebar: [{ type: "autogenerated", dirName: "computer-science" }],
  statusSystemSidebar: ["status-system"],
};

export default sidebars;
